drop table folders, notes;

--drop table if exists folders;

create table folders (
  id INTEGER primary key generated by default as identity,
  folder_name text not null
);



-- create table folders (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   folder_name text not null
-- );