drop table if exists notes;

create table notes (
  id INTEGER primary key generated by default as identity,
  note_name text not null,
  modified TIMESTAMP not null default now(), 
  content text,
  folder_id integer REFERENCES folders(id) ON DELETE CASCADE NOT NULL
);

-- create table notes (
--   id INTEGER primary key generated by default as identity,
--   note_name text not null,
--   modified TIMESTAMP not null default now(), 
--   content text,
--   folder_id integer REFERENCES folders(id) NOT NULL
-- );


-- create table notes (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   note_name text not null,
--   modified TIMESTAMP not null default now(), 
--   content text,
--   folder_id integer REFERENCES folders(id) ON DELETE CASCADE NOT NULL
-- );