create table notes (
  id INTEGER primary key generated by default as identity,
  note_name text not null,
  modified TIMESTAMP not null default now(), 
  content text,
  folder_id integer REFERENCES folders(id) NOT NULL
);